FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src

COPY BrioBook.Account/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o build

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT [ "dotnet", "BrioBook.Account.dll" ]
