FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src

COPY BrioBook.Account/BrioBook.Account.csproj BrioBook.Account/BrioBook.Account.csproj
COPY BrioBook.Users.DAL/BrioBook.Users.DAL.csproj BrioBook.Users.DAL/BrioBook.Users.DAL.csproj
RUN dotnet restore BrioBook.Account/BrioBook.Account.csproj

COPY . .
WORKDIR /src
RUN dotnet build BrioBook.Account/BrioBook.Account.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish BrioBook.Account/BrioBook.Account.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT [ "dotnet", "BrioBook.Account.dll" ]