FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY *.sln .
COPY BrioBook.Account/BrioBook.Account.csproj src/BrioBook.Account/

RUN dotnet restore

COPY . .

FROM build AS publish
RUN dotnet publish -c release -o /app --no-restore
 
FROM base AS runtime

WORKDIR /app

COPY --from=publish /app .

ENTRYPOINT [ "dotnet", "BrioBook.Account.dll" ]